name: Docs Reviewer Nomination Template
description: Nominate yourself or someone else to become a documentation reviewer.
title: 'Documentation Reviewer Nomination: <username>'
labels: nomination/docs-reviewer
body:
  - type: markdown
    attributes:
      value: |
        The Documentation and Community SIG maintains several reviewer roles requiring SIG approval - this nomination form is for serving as a _documentation reviewer_, responsible for reviewing contributions to `o3de.org/docs`. Documentation reviewers are expected to:

        * Help guide structure and intent of documentation submissions. Writing documentation is hard and often a subjective exercise, so reviewers are expected to exercise both their best judgement and follow common site structure and [templates](https://www.o3de.org/docs/contributing/to-docs/templates/) where available.
        * Help ensure consistency of product [terminology](https://www.o3de.org/docs/contributing/to-docs/terminology/).
        * Review content submissions with an eye towards following the [style guide](https://www.o3de.org/docs/contributing/to-docs/style-guide/).
        * Review 4+ pull requests per month, or as-assigned. Under light PR load, these requirements are relaxed. Not meeting this requirement for two months in a row results in loss of reviewer status.

        **Maintaining status:** 4+ Pull Requests reviewed per month, or as-assigned. Under light PR load, these requirements are relaxed. Not meeting this requirement for two months in a row results in loss of reviewer status.

        For more on the general requirements of Reviewer roles, read our [Community Membership](https://github.com/o3de/community/blob/main/community-membership.md) information.
  - type: input
    id: username
    attributes:
      label: Nominee GitHub user name
      placeholder: username
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Link to relevant pull requests or comments that demonstrate meeting the requirements.
      placeholder: |
        * <links to relevant pull requests or comments>
        * ...
    validations:
      required: true
  - type: textarea
    id: information
    attributes:
      label: Support statement  (Optional)
      description: If you'd like, include a brief statement about why you support this nomination.
  - type: checkboxes
    id: approvals
    attributes:
      label: '**BOXES TO BE CHECKED NOMINATION REVIEW**'
      options:
        - label: |
          6+ merged documentation contributions for the O3DE project. The following count as documentation contributions:
          
          * Contributions to any section of https://o3de.org/docs requiring review by a sig-docs-community non-technical review group.
          * Contributions to accepted sig-docs-community RFCs related to documentation. This may include operational support as well as technical writing.
          * High-quality error messages, tooltips, UI text, or API documentation submitted to https://github.com/o3de/o3de involving approval of at least one documentation reviewer.
        - label: 2+ docs or community reviewers or Maintainers of the Documentation and Community SIG approve the nomination.
